import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="relative mx-auto  bg-slate-900 text-white min-h-screen">
          <div className="container mx-auto">
            <div className="py-16 px-4 sm:px-6 lg:px-8">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
